on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Сафонов Артемий"
      GROUP_NUMBER: "M3111"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print info
        run: |
          echo "ФИО: ${{ env.FULL_NAME }}"
          echo "Группа: ${{ env.GROUP_NUMBER }}"
          echo "Github Nick: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests/

      - name: Run lint (flake8 example)
        run: pip install flake8 && flake8
